name = "create-aeronautics"
author = "Me"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b20e0bcc691f530638b5810d35f6220e3889ce75ade98a1afe6c236cf2ed2b5c"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.251"
