name = "create-aeronautics"
author = "Me"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fa9ae65376dcf95cedf3aadf9ed3887fa7464023b2a721a9e5d34b69d2fdbd58"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.251"
