name = "create-aeronautics"
author = "Me"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a0bc1d54ca4f01c2fb237359a63d070f77232d2a8a042382a83c352188cc19fb"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.251"
